import { DOCS_ORIGIN } from "@/lib/links";

export const chapters = [
  {
    id: "request",
    label: "A request",
    title: "It starts with a question.",
    description:
      "Someone asks your app, ‘Where’s my order?’ Behind that little message, an agent calls a model, looks up the order, and writes an answer.",
    note: "Think of your app as a workshop. Each station has a job. A request moves between them until the work is done.",
    color: "#a4522f",
    x: 25,
    y: 73,
    station: "The front door",
    href: "/features/sdk",
    link: "Connect your app",
  },
  {
    id: "traces",
    label: "Traces",
    title: "Follow the work inside.",
    description:
      "Foglamp records each AI call as a trace. Inside it, smaller steps called spans show the model calls and tools, with their inputs, outputs, and timing.",
    note: "The order lookup says ‘delayed.’ The answer says ‘arrives today.’ Following the trace shows where those two stopped agreeing.",
    color: "#856044",
    x: 78,
    y: 63,
    station: "The order lookup",
    href: "/features/distributed-traces",
    link: "Explore traces",
  },
  {
    id: "agents",
    label: "Agents",
    title: "Meet the agent doing the work.",
    description:
      "An agent uses instructions, models, and tools to work on a task. Give it a name, and Foglamp brings its runs, costs, and errors together.",
    note: "Instructions change, too. Foglamp finds prompt versions in your recorded runs, so you can compare what changed and see which runs used each version.",
    color: "#b65c30",
    x: 44,
    y: 65,
    station: "The agent’s desk",
    href: "/features/agents",
    link: "Get to know your agents",
  },
  {
    id: "workflows",
    label: "Workflows",
    title: "Some jobs take a team.",
    description:
      "One agent sorts the question. Another checks the order. A workflow run groups the AI calls that belong to one job, even when different agents do the work.",
    note: "Your code controls the steps and branches. Add a workflow name and run ID, and Foglamp brings the recorded calls into one view.",
    color: "#527473",
    x: 58,
    y: 48,
    station: "The connecting paths",
    href: `${DOCS_ORIGIN}/dashboard/workflows`,
    link: "See how workflows connect",
  },
  {
    id: "sessions",
    label: "Sessions",
    title: "A conversation keeps going.",
    description:
      "The customer asks a follow-up. A session connects the traces in the same conversation, so you can understand the experience across several messages.",
    note: "Workflows group calls for a job. Sessions group calls for a conversation. The same trace can belong to both.",
    color: "#567e63",
    x: 26,
    y: 86,
    station: "The message trail",
    href: `${DOCS_ORIGIN}/dashboard/sessions`,
    link: "See the whole conversation",
  },
  {
    id: "costs",
    label: "Costs",
    title: "Small calls add up.",
    description:
      "Each model call takes time and uses tokens, the pieces of text a model reads and writes. Foglamp tracks usage, cost, and latency so you can see where they go.",
    note: "Pull back to see patterns by model, agent, or customer. Then open an individual trace to understand an expensive or slow run.",
    color: "#437358",
    x: 30,
    y: 34,
    station: "The counting room",
    href: "/features/cost-intelligence",
    link: "Explore cost intelligence",
  },
  {
    id: "evals",
    label: "Evals",
    title: "An answer can work and still be wrong.",
    description:
      "Evaluations check the quality of an answer. Code checks test clear rules, like valid JSON. LLM judges assess things like helpfulness or whether an answer agrees with its sources.",
    note: "The inspection bench checks copies of recorded traffic. Choose which traces or steps to sample, review their scores, and open the ones that failed.",
    color: "#925779",
    x: 66,
    y: 33,
    station: "The inspection bench",
    href: "/features/evals",
    link: "Explore evaluations",
  },
  {
    id: "alerts",
    label: "Alerts",
    title: "Know when something needs you.",
    description:
      "Set a limit for cost, latency, error rate, or an eval’s pass rate. Foglamp checks recent traffic every minute and sends an email when a rule fires.",
    note: "Start with the alert, inspect its context and relevant traces, then follow the work back to the problem. The rule returns to healthy when the metric recovers.",
    color: "#95701f",
    x: 87,
    y: 14,
    station: "The watchtower",
    href: "/features/alerts",
    link: "Explore alerts",
  },
] as const;
