import type { Metadata } from "next";

import { CtaSection } from "@/components/marketing/landing/cta";
import { ScanHero } from "./scan-hero";
import { ScanStory } from "./scan-story";

export const metadata: Metadata = {
  title: "Foglamp Scan",
  description:
    "A beautiful, shareable map of how your codebase uses AI. Generated by your own coding agent. No install, no account.",
  openGraph: {
    title: "Foglamp Scan",
    description:
      "One prompt turns your repo into a beautiful, interactive map of how it uses AI.",
  },
  alternates: { canonical: "/scan" },
};

export default function ScanLandingPage() {
  return (
    <div className="flex flex-col gap-36">
      <ScanHero />
      <ScanStory />
      <CtaSection />
    </div>
  );
}
