import type { Metadata } from "next";

import { ScanLanding } from "./scan-landing";

export const metadata: Metadata = {
	title: "Foglamp Scan",
	description:
		"A beautiful, shareable map of your codebase. Generated by your own coding agent. No install, no account.",
	openGraph: {
		title: "Foglamp Scan",
		description:
			"One prompt turns your repo into a beautiful, interactive map.",
	},
	alternates: { canonical: "/scan" },
};

export default function ScanLandingPage() {
	return <ScanLanding />;
}
